compute_environment: LOCAL_MACHINE
deepspeed_config: ./ds_zero3_config.json
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 20222
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
use_cpu: false