compute_environment: LOCAL_MACHINE
deepspeed_config:
<<<<<<< HEAD:accelerate_config_zero3.yaml
  deepspeed_config_file: /home/v-boli7/projects/PET-VLM/ds_config.json
  # gradient_accumulation_steps: 1
  # gradient_clipping: 1.0
  # offload_optimizer_device: cpu
  # offload_param_device: cpu
  # zero3_init_flag: true
  # zero3_save_16bit_model: true
  # zero_stage: 3
=======
  deepspeed_config_file: ds_config.json
  zero3_init_flag: true
>>>>>>> debug LLava:accelerate_config.yaml
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
  dynamo_mode: default
  dynamo_use_dynamic: false
  dynamo_use_fullgraph: true
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
