training_data:
  - mimicit: /home/luodian/projects/Otter/archived/VideoQA_Instruction.json
    images: /home/luodian/projects/Otter/archived/VideoQA_Images.json
  - mimicit: /home/luodian/projects/data/DC/DC_instructions.json
    images: /home/luodian/projects/data/DC/DC_images.json
