 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  laion2B_multi:

    data_type: images

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      storage: /export/laion/laion2B-multi/part-00000/{00000..01743}.tar
