datasets:
  - name: mmbench
    version: 20230712
    split: test
    # cache_dir: /path/to/hf/cache

models:
  - name: idefics
    model_path: /home/luodian/azure_storage/otter/checkpoints/Otter_Idefics_1005_TaskDesc
  # - name: idefics_otter
  #   model_path: /path/to/checkpoints/otter_idefics9b_0830
  #   processor: /path/to/checkpoints/idefics-9b-instruct
